version: "3"
services:
    db:
        image: "mysql:5.7"
        restart: always

        volumes:
            - "db_data:/var/lib/mysql"

        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

        networks:
            - wp

    wordpress:
        depends_on:
            - db

        image: "wordpress:6"
        restart: always

        volumes:
            - "./local-wp:/var/www/html"
            - "./wp-content:/var/www/html/wp-content"
            - "./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"

        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

        ports:
            - "8080:80"

        networks:
            - wp

    phpmyadmin:
        depends_on:
            - db

        image: phpmyadmin/phpmyadmin
        restart: always

        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
            UPLOAD_LIMIT: 512M

        ports:
            - "8081:80"

        networks:
            - wp

networks:
    wp:

volumes:
    db_data: