version: "3"
services:
    db:
        image: "mysql:5.7"
        restart: always

        volumes:
            - "db_data:/var/lib/mysql"

        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

        networks:
            - wp

    wordpress:
        depends_on:
            - db

        image: "wordpress:4.9"
        restart: always

        volumes: ["./:/var/www/html"]

        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

        ports:
            - "8080:80"

        networks:
            - wp

    phpmyadmin:
        depends_on:
            - db

        image: phpmyadmin/phpmyadmin
        restart: always

        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password

        volumes:
            - "./config/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini"

        ports:
            - "8081:80"

        networks:
            - wp

networks:
    wp:

volumes:
    db_data:
